name: Build Cross-Platform Executables

on:
  push:
    branches: [ "main", "master" ] # Draai dit script bij een push naar de main/master branch
  pull_request:
    branches: [ "main", "master" ] # Draai ook bij een pull request naar main/master
  workflow_dispatch: # Maakt het mogelijk om de build handmatig te starten

jobs:
  build:
    # Gebruik een matrix om de job op meerdere besturingssystemen te draaien
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Gebruik dezelfde Python-versie als lokaal

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Deze stap stelt de naam van de executable in op basis van het OS
    - name: Set executable name
      id: set_name
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          echo "exe_name=dobbelsteen_simulatie.exe" >> $GITHUB_ENV
        else
          echo "exe_name=dobbelsteen_simulatie" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Build with PyInstaller
      run: |
        # Start met de basis-argumenten
        PYINSTALLER_ARGS="--onefile --windowed --hidden-import PIL._tkinter_finder"

        # Voeg het icoon-argument conditioneel toe
        if [[ "${{ runner.os }}" == "Windows" && -f "assets/dice.ico" && -f "version.py" ]]; then
          PYINSTALLER_ARGS="$PYINSTALLER_ARGS --icon=assets/dice.ico --version-file version.py"
        elif [[ "${{ runner.os }}" == "macOS" && -f "assets/dice.icns" ]]; then
          PYINSTALLER_ARGS="$PYINSTALLER_ARGS --icon=assets/dice.icns"
        fi

        # Voer PyInstaller uit met de samengestelde argumenten
        pyinstaller $PYINSTALLER_ARGS dobbelsteen_simulatie.py
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dobbelsteen-simulatie-${{ runner.os }}
        path: dist/${{ steps.set_name.outputs.exe_name }}

  release:
    # De 'release' job draait alleen als de 'build' job succesvol is voor alle OS'en
    needs: build
    runs-on: ubuntu-latest
    # Draai deze job alleen bij een push naar de main branch, niet bij pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: Generate release tag
      id: tag
      # Gebruik de 'pushed_at' tijd van de repository voor een deterministische tag.
      # De '@' voor de timestamp geeft aan dat het een Unix epoch tijd is.
      run: echo "release_tag=release-$(date -u -d @${{ github.event.repository.pushed_at }} +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

    - name: Create Release and Upload Artifacts
      uses: softprops/action-gh-release@v2
      with:
        # Maak een tag aan op basis van de datum en tijd, bv. 'release-20240815123000'
        tag_name: ${{ steps.tag.outputs.release_tag }}
        # Gebruik de laatste commit message als de body van de release notes
        body: |
          Automatische release van de laatste wijzigingen.
          Commit: ${{ github.sha }}
        make_latest: true # Markeer deze release als de 'latest'
        files: |
          artifacts/dobbelsteen-simulatie-windows-latest/dobbelsteen_simulatie.exe
          artifacts/dobbelsteen-simulatie-macos-latest/dobbelsteen_simulatie
          artifacts/dobbelsteen-simulatie-ubuntu-latest/dobbelsteen_simulatie