name: Build Cross-Platform Executables

on:
  push:
    branches: [ "main", "master" ] # Draai dit script bij een push naar de main/master branch
  workflow_dispatch: # Maakt het mogelijk om de build handmatig te starten

jobs:
  build:
    # Gebruik een matrix om de job op meerdere besturingssystemen te draaien
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Gebruik dezelfde Python-versie als lokaal

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # Deze stap stelt de naam van de executable in op basis van het OS
    - name: Set executable name
      id: set_name
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          echo "exe_name=dobbelsteen_simulatie.exe" >> $GITHUB_ENV
        else
          echo "exe_name=dobbelsteen_simulatie" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Build with PyInstaller
      run: |
        # Bepaal het icoon-argument op basis van het besturingssysteem
        ICON_ARG=""
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          # Controleer of het icoonbestand bestaat
          if [ -f "assets/dice.ico" ]; then
            ICON_ARG="--icon=assets/dice.ico"
          fi
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          # Controleer of het icoonbestand bestaat
          if [ -f "assets/dice.icns" ]; then
            ICON_ARG="--icon=assets/dice.icns"
          fi
        fi

        # Voer PyInstaller uit met de juiste argumenten
        pyinstaller --onefile --windowed --hidden-import PIL._tkinter_finder $ICON_ARG dobbelsteen_simulatie.py
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dobbelsteen-simulatie-${{ runner.os }}
        path: dist/${{ env.exe_name }}