name: Build Executable

on:
  push:
    branches: [ "main", "master" ] # Draai dit script bij een push naar de main/master branch
  workflow_dispatch: # Maakt het mogelijk om de build handmatig te starten

jobs:
  build-windows:
    runs-on: windows-latest  # Gebruik de nieuwste Windows-versie die GitHub aanbiedt

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Gebruik dezelfde Python-versie als lokaal

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed --hidden-import PIL._tkinter_finder dobbelsteen_simulatie.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dobbelsteen-simulatie-windows
        path: dist/dobbelsteen_simulatie.exe