# .github/workflows/cleanup-releases.yml
name: Delete old releases
on:
  schedule:
    # Runs at 01:00 every day to avoid conflicts with other scheduled jobs.
    - cron: '0 1 * * *'
  workflow_dispatch: # Allows you to run this workflow manually

jobs:
  delete-old-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to delete releases and their tags.

    steps:
      - name: Delete releases older than the 3 most recent
        uses: dev-drpr/delete-older-releases@v0.4.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}